version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: MusicApp
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: MusicApp
      MYSQL_USER: user
      MYSQL_USER_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql: